### PR TITLE
Add keyboard shortcuts for common actions.

### PR DESCRIPTION
**Pull request by koppi**
This PR adds more keyboard shortcuts for common actions.

### CODE REVIEW

**Comment by jcoffland** [comment]
This is great.  Thanks.  I've got a couple of issue though.

  1. What are all the margin changes about?
  2. I think either ``CTRL-R`` or ``F12`` should be save all and rerun the simulation.  That's what these keys are often used for.
  3. It would be better if this PR was against the ``dev`` branch.  I'm getting ready to merge ``dev`` into ``master``.  ``dev`` has all the latest code.

**Comment by koppi** [comment]
1. Margin changes came from Qt Creator:
```bash
$ dpkg -l|grep qtcreator
ii  qtcreator                                            3.1.1-0ubuntu10        
```
2. I will remove ```CTRL-R``` and ```F12``` from my PR.
3. I will close this PR and create a new PR against ```dev```.

**Comment by jcoffland** [comment]
Ok, thanks.  Sounds good.

**Comment by koppi** [comment]
Unfortunately my Qt Creator version removes the resource xml tags, see diff:
```diff
diff --git a/qt/openscam.ui b/qt/openscam.ui
index 1b54d17..58c499b 100644
--- a/qt/openscam.ui
+++ b/qt/openscam.ui
@@ -18,7 +18,7 @@
    <string>OpenSCAM[*]</string>
   </property>
   <property name="windowIcon">
-   <iconset resource="openscam.qrc">
+   <iconset>
     <normaloff>:/icons/openscam.png</normaloff>:/icons/openscam.png</iconset>
   </property>
   <property name="styleSheet">
@@ -251,7 +251,7 @@
              <string/>
             </property>
             <property name="icon">
-             <iconset resource="openscam.qrc">
+             <iconset>
               <normaloff>:/icons/clear.png</normaloff>:/icons/clear.png</iconset>
             </property>
            </widget>
@@ -340,7 +340,7 @@
      <x>0</x>
      <y>0</y>
      <width>1004</width>
-     <height>29</height>
+     <height>25</height>
     </rect>
    </property>
    <widget class="QMenu" name="menuFile">
@@ -2645,7 +2645,7 @@
   </widget>
   <action name="actionNew">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/new.png</normaloff>:/icons/new.png</iconset>
    </property>
    <property name="text">
@@ -2654,6 +2654,9 @@
    <property name="toolTip">
     <string>Create a new project.</string>
    </property>
+   <property name="shortcut">
+    <string>Ctrl+N</string>
+   </property>
   </action>
   <action name="actionOpen">
    <property name="icon">
@@ -2667,10 +2670,13 @@
    <property name="toolTip">
     <string>Open an existing project or NC file.</string>
    </property>
+   <property name="shortcut">
+    <string>Ctrl+O</string>
+   </property>
   </action>
   <action name="actionSave">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/save.png</normaloff>:/icons/save.png</iconset>
    </property>
    <property name="text">
@@ -2682,16 +2688,19 @@
   </action>
   <action name="actionSaveAs">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/save_as.png</normaloff>:/icons/save_as.png</iconset>
    </property>
    <property name="text">
     <string>Save Project &amp;As</string>
    </property>
+   <property name="shortcut">
+    <string>Ctrl+Shift+S</string>
+   </property>
   </action>
   <action name="actionExport">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/export.png</normaloff>:/icons/export.png</iconset>
    </property>
    <property name="text">
@@ -2700,10 +2709,13 @@
    <property name="toolTip">
     <string>Export the surface</string>
    </property>
+   <property name="shortcut">
+    <string>Ctrl+E</string>
+   </property>
   </action>
   <action name="actionSnapshot">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/snapshot.png</normaloff>:/icons/snapshot.png</iconset>
    </property>
    <property name="text">
@@ -2715,16 +2727,19 @@
   </action>
   <action name="actionQuit">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/quit.png</normaloff>:/icons/quit.png</iconset>
    </property>
    <property name="text">
     <string>&amp;Quit</string>
    </property>
+   <property name="shortcut">
+    <string>Ctrl+Q</string>
+   </property>
   </action>
   <action name="actionAbout">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/about.png</normaloff>:/icons/about.png</iconset>
    </property>
    <property name="text">
@@ -2736,7 +2751,7 @@
     <bool>true</bool>
    </property>
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/wire.png</normaloff>:/icons/wire.png</iconset>
    </property>
    <property name="text">
@@ -2754,7 +2769,7 @@
     <bool>true</bool>
    </property>
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/bbox.png</normaloff>:/icons/bbox.png</iconset>
    </property>
    <property name="text">
@@ -2775,7 +2790,7 @@
     <bool>true</bool>
    </property>
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/tool.png</normaloff>:/icons/tool.png</iconset>
    </property>
    <property name="text">
@@ -2793,7 +2808,7 @@
     <bool>true</bool>
    </property>
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/cut_surface.png</normaloff>:/icons/cut_surface.png</iconset>
    </property>
    <property name="text">
@@ -2814,7 +2829,7 @@
     <bool>true</bool>
    </property>
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/axes.png</normaloff>:/icons/axes.png</iconset>
    </property>
    <property name="text">
@@ -2832,7 +2847,7 @@
     <bool>true</bool>
    </property>
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/path.png</normaloff>:/icons/path.png</iconset>
    </property>
    <property name="text">
@@ -2844,7 +2859,7 @@
   </action>
   <action name="actionIsoView">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/isometric.png</normaloff>:/icons/isometric.png</iconset>
    </property>
    <property name="text">
@@ -2859,7 +2874,7 @@
   </action>
   <action name="actionFrontView">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/front.png</normaloff>:/icons/front.png</iconset>
    </property>
    <property name="text">
@@ -2874,7 +2889,7 @@
   </action>
   <action name="actionBackView">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/back.png</normaloff>:/icons/back.png</iconset>
    </property>
    <property name="text">
@@ -2889,7 +2904,7 @@
   </action>
   <action name="actionLeftView">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/left.png</normaloff>:/icons/left.png</iconset>
    </property>
    <property name="text">
@@ -2904,7 +2919,7 @@
   </action>
   <action name="actionRightView">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/right.png</normaloff>:/icons/right.png</iconset>
    </property>
    <property name="text">
@@ -2919,7 +2934,7 @@
   </action>
   <action name="actionTopView">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/top.png</normaloff>:/icons/top.png</iconset>
    </property>
    <property name="text">
@@ -2934,7 +2949,7 @@
   </action>
   <action name="actionBottomView">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/bottom.png</normaloff>:/icons/bottom.png</iconset>
    </property>
    <property name="text">
@@ -2949,7 +2964,7 @@
   </action>
   <action name="actionBegining">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/start.png</normaloff>:/icons/start.png</iconset>
    </property>
    <property name="text">
@@ -2961,7 +2976,7 @@
   </action>
   <action name="actionSlower">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/slower.png</normaloff>:/icons/slower.png</iconset>
    </property>
    <property name="text">
@@ -2973,7 +2988,7 @@
   </action>
   <action name="actionPlay">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/play.png</normaloff>:/icons/play.png</iconset>
    </property>
    <property name="text">
@@ -2985,7 +3000,7 @@
   </action>
   <action name="actionFaster">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/faster.png</normaloff>:/icons/faster.png</iconset>
    </property>
    <property name="text">
@@ -2997,7 +3012,7 @@
   </action>
   <action name="actionEnd">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/end.png</normaloff>:/icons/end.png</iconset>
    </property>
    <property name="text">
@@ -3009,7 +3024,7 @@
   </action>
   <action name="actionDirection">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/forward.png</normaloff>:/icons/forward.png</iconset>
    </property>
    <property name="text">
@@ -3021,7 +3036,7 @@
   </action>
   <action name="actionAddTool">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/add.png</normaloff>:/icons/add.png</iconset>
    </property>
    <property name="text">
@@ -3033,7 +3048,7 @@
   </action>
   <action name="actionRemoveTool">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/remove.png</normaloff>:/icons/remove.png</iconset>
    </property>
    <property name="text">
@@ -3045,7 +3060,7 @@
   </action>
   <action name="actionAddFile">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/add.png</normaloff>:/icons/add.png</iconset>
    </property>
    <property name="text">
@@ -3057,7 +3072,7 @@
   </action>
   <action name="actionRemoveFile">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/remove.png</normaloff>:/icons/remove.png</iconset>
    </property>
    <property name="text">
@@ -3072,7 +3087,7 @@
     <bool>true</bool>
    </property>
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/no-surface.png</normaloff>:/icons/no-surface.png</iconset>
    </property>
    <property name="text">
@@ -3084,7 +3099,7 @@
   </action>
   <action name="actionStop">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/stop.png</normaloff>:/icons/stop.png</iconset>
    </property>
    <property name="text">
@@ -3099,7 +3114,7 @@
   </action>
   <action name="actionRun">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/restart.png</normaloff>:/icons/restart.png</iconset>
    </property>
    <property name="text">
@@ -3117,7 +3132,7 @@
     <bool>false</bool>
    </property>
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/reduce.png</normaloff>:/icons/reduce.png</iconset>
    </property>
    <property name="text">
@@ -3129,7 +3144,7 @@
   </action>
   <action name="actionDonate">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/donate.png</normaloff>:/icons/donate.png</iconset>
    </property>
    <property name="text">
@@ -3144,7 +3159,7 @@
     <bool>true</bool>
    </property>
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/surface.png</normaloff>:/icons/surface.png</iconset>
    </property>
    <property name="text">
@@ -3206,7 +3221,7 @@
   </action>
   <action name="actionHelp">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/help.png</normaloff>:/icons/help.png</iconset>
    </property>
    <property name="text">
@@ -3218,7 +3233,7 @@
     <bool>false</bool>
    </property>
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/revert.png</normaloff>:/icons/revert.png</iconset>
    </property>
    <property name="text">
@@ -3233,7 +3248,7 @@
     <bool>false</bool>
    </property>
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/save_as.png</normaloff>:/icons/save_as.png</iconset>
    </property>
    <property name="text">
@@ -3248,7 +3263,7 @@
     <bool>false</bool>
    </property>
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/save.png</normaloff>:/icons/save.png</iconset>
    </property>
    <property name="text">
@@ -3260,7 +3275,7 @@
   </action>
   <action name="actionUndo">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/undo.png</normaloff>:/icons/undo.png</iconset>
    </property>
    <property name="text">
@@ -3275,7 +3290,7 @@
   </action>
   <action name="actionRedo">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/redo.png</normaloff>:/icons/redo.png</iconset>
    </property>
    <property name="text">
@@ -3290,7 +3305,7 @@
   </action>
   <action name="actionCut">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/cut.png</normaloff>:/icons/cut.png</iconset>
    </property>
    <property name="text">
@@ -3305,7 +3320,7 @@
   </action>
   <action name="actionCopy">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/copy.png</normaloff>:/icons/copy.png</iconset>
    </property>
    <property name="text">
@@ -3320,7 +3335,7 @@
   </action>
   <action name="actionPaste">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/paste.png</normaloff>:/icons/paste.png</iconset>
    </property>
    <property name="text">
@@ -3335,7 +3350,7 @@
   </action>
   <action name="actionSelectAll">
    <property name="icon">
-    <iconset resource="openscam.qrc">
+    <iconset>
      <normaloff>:/icons/select-all.png</normaloff>:/icons/select-all.png</iconset>
    </property>
    <property name="text">
@@ -3356,9 +3371,7 @@
    <header>openscam/qt/GLView.h</header>
   </customwidget>
  </customwidgets>
- <resources>
-  <include location="openscam.qrc"/>
- </resources>
+ <resources/>
  <connections/>
  <buttongroups>
   <buttongroup name="buttonGroup"/>
```

**Comment by jcoffland** [comment]
I've just manually added these shortcuts.  Thanks for the PR.

**Comment by koppi** [comment]
Thank's @jcoffland !

**Pull request closed without merging**
